"""Pydantic schemas package."""

from app.schemas.ai_analysis import (
    AIAnalysisContext,
    AIAnalysisResultResponse,
    AIAttachmentEvidence,
    AICaseContext,
    AIDomainEvidence,
    AIEmailContext,
    AIForensicEvidence,
    AIHeaderEvidence,
    AIIPAddressEvidence,
    AIThreatAssessment,
    AIThreatIndicator,
    AIThreatIntelligence,
    AIThreatIntelResult,
    AIURLEvidence,
)
from app.schemas.email_analysis import (
    EmailAnalysisResponse,
    ParsedAttachment,
    ParsedDomain,
    ParsedEmailData,
    ParsedHeader,
    ParsedIP,
    ParsedURL,
)

__all__ = [
    "AIAnalysisContext",
    "AIAnalysisResultResponse",
    "AIAttachmentEvidence",
    "AICaseContext",
    "AIDomainEvidence",
    "AIEmailContext",
    "AIForensicEvidence",
    "AIHeaderEvidence",
    "AIIPAddressEvidence",
    "AIThreatAssessment",
    "AIThreatIndicator",
    "AIThreatIntelligence",
    "AIThreatIntelResult",
    "AIURLEvidence",
    "EmailAnalysisResponse",
    "ParsedAttachment",
    "ParsedDomain",
    "ParsedEmailData",
    "ParsedHeader",
    "ParsedIP",
    "ParsedURL",
]
