"""Pydantic schemas package."""

from app.schemas.ai_analysis import (
    AIAnalysisContext,
    AIAnalysisResultResponse,
    AIAttachmentEvidence,
    AICaseContext,
    AIDomainEvidence,
    AIEmailContext,
    AIForensicEvidence,
    AIHeaderEvidence,
    AIIPAddressEvidence,
    AIThreatAssessment,
    AIThreatIndicator,
    AIThreatIntelligence,
    AIThreatIntelResult,
    AIURLEvidence,
)
from app.schemas.email_analysis import (
    EmailAnalysisResponse,
    ParsedAttachment,
    ParsedDomain,
    ParsedEmailData,
    ParsedHeader,
    ParsedIP,
    ParsedURL,
)
from app.schemas.investigation import (
    AttachmentItem,
    CaseListItem,
    CaseListResponse,
    CaseWorkspaceResponse,
    DomainItem,
    EmailWorkspaceItem,
    HeaderItem,
    InvestigationEventItem,
    InvestigationSummary,
    IpItem,
    ThreatIntelItem,
    UrlItem,
)
from app.schemas.investigation_detail import EmailDetailResponse
from app.schemas.evidence import (
    EvidenceItem,
    EvidenceListResponse,
    EventListResponse,
    IndicatorListResponse,
    InvestigationEventItem as EvidenceEventItem,
    ThreatIndicatorItem,
)

__all__ = [
    "AIAnalysisContext",
    "AIAnalysisResultResponse",
    "AIAttachmentEvidence",
    "AICaseContext",
    "AIDomainEvidence",
    "AIEmailContext",
    "AIForensicEvidence",
    "AIHeaderEvidence",
    "AIIPAddressEvidence",
    "AIThreatAssessment",
    "AIThreatIndicator",
    "AIThreatIntelligence",
    "AIThreatIntelResult",
    "AIURLEvidence",
    "AttachmentItem",
    "CaseListItem",
    "CaseListResponse",
    "CaseWorkspaceResponse",
    "DomainItem",
    "EmailAnalysisResponse",
    "EmailDetailResponse",
    "EmailWorkspaceItem",
    "HeaderItem",
    "InvestigationEventItem",
    "InvestigationSummary",
    "IpItem",
    "ParsedAttachment",
    "ParsedDomain",
    "ParsedEmailData",
    "ParsedHeader",
    "ParsedIP",
    "ParsedURL",
    "ThreatIntelItem",
    "ThreatIndicatorItem",
    "UrlItem",
    "EvidenceItem",
    "EvidenceListResponse",
    "EvidenceEventItem",
    "EventListResponse",
    "IndicatorListResponse",
]
